### ISSUE TITLE
aux.sch

### ISSUE THREAD

**Issue by DivingDuck** [andrimarjonsson/mks-sbase-schematic#1]
I try to clone your repository and get an error with aux.sch: Invalid path: aux.sch. Seems this is a protected name for Windows.

**Comment by andrimarjonsson** [comment]
@DivingDuck Excuse the late reply.
This is very interesting. I'll give this a try as soon as I can on a Windows machine, might be a few days.

**Comment by andrimarjonsson** [comment]
...or maybe I don't need to do that even. The file is no longer used, somewhere in the reverse engineering process I renamed the aux sheet to aux_sd and Kicad does not rename the underlying file, it simply creates a new one with the new name.

Just pushed a change that removes that file. Hopefully that is enough for you to be able to clone this repository without errors.

**Comment by DivingDuck** [comment]
@andrimarjonsson, Thanks a lot for looking and updating. I appreciate your work. I used it to identify a problem with my board. Ethernet wasn't working because of missing power...
Best regards, DD
